# Generated by Django 2.2.3 on 2019-07-15 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='asin',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
